import { $random, RandomArray } from '@random-fixtures/core';

declare module '@random-fixtures/core' {
  interface RandomRegistry {
    address: Address;
  }
}

class Address {
  private cities: RandomArray<string> = RandomArray.of(
    'Abidjan',
    'Abuja',
    'Addis Ababa',
    'Ahmedabad',
    'Alexandria',
    'Algiers',
    'Almaty',
    'Amman',
    'Amritsar',
    'Amsterdam',
    'Ankara',
    'Antananarivo',
    'Athens',
    'Austin',
    'Baghdad',
    'Baku',
    'Bangalore',
    'Bangkok',
    'Barcelona',
    'Baton Rouge',
    'Beijing',
    'Beirut',
    'Belgrade',
    'Belo Horizonte',
    'Bengaluru',
    'Berlin',
    'Birmingham',
    'Bishkek',
    'Bogotá',
    'Bordeaux',
    'Boston',
    'Brisbane',
    'Brussels',
    'Bucharest',
    'Budapest',
    'Buenos Aires',
    'Busan',
    'Cairo',
    'Cali',
    'Cape Town',
    'Caracas',
    'Casablanca',
    'Chennai',
    'Chicago',
    'Chongqing',
    'Cologne',
    'Colombo',
    'Copenhagen',
    'Dakar',
    'Dallas',
    'Dar es Salaam',
    'Delhi',
    'Denver',
    'Dhaka',
    'Dublin',
    'Durban',
    'Edinburgh',
    'Faisalabad',
    'Florence',
    'Fortaleza',
    'Frankfurt',
    'Fukuoka',
    'Fuzhou',
    'Giza',
    'Glasgow',
    'Guangzhou',
    'Guayaquil',
    'Hamburg',
    'Hanoi',
    'Harare',
    'Harbin',
    'Havana',
    'Helsinki',
    'Ho Chi Minh City',
    'Hong Kong',
    'Honolulu',
    'Houston',
    'Hyderabad',
    'Ibadan',
    'Indore',
    'Istanbul',
    'Izmir',
    'Jacksonville',
    'Jaipur',
    'Jeddah',
    'Jinan',
    'Johannesburg',
    'Karachi',
    'Karaj',
    'Kathmandu',
    'Khartoum',
    'Kiev',
    'Kinshasa',
    'Kobe',
    'Kolkata',
    'Krasnoyarsk',
    'Kunming',
    'Kyoto',
    'Lagos',
    'Lahore',
    'Las Vegas',
    'Leeds',
    'Lille',
    'Lima',
    'Lincoln',
    'Lisbon',
    'London',
    'Los Angeles',
    'Lucknow',
    'Luanda',
    'Lusaka',
    'Lviv',
    'Lyon',
    'Madrid',
    'Makassar',
    'Manchester',
    'Managua',
    'Manila',
    'Marseille',
    'Medan',
    'Medellín',
    'Melbourne',
    'Mexico City',
    'Miami',
    'Milan',
    'Minsk',
    'Monterrey',
    'Montevideo',
    'Montreal',
    'Mumbai',
    'Munich',
    'Nagoya',
    'Nagpur',
    'Nairobi',
    'Nanchang',
    'Nanjing',
    'Nashik',
    'New York',
    'Newcastle',
    'Nice',
    'Niamey',
    'Ningbo',
    'Nuremberg',
    'Oakland',
    'Odessa',
    'Odesa',
    'Oklahoma City',
    'Omdurman',
    'Orlando',
    'Osaka',
    'Ottawa',
    'Ouagadougou',
    'Palermo',
    'Paris',
    'Pattaya',
    'Perth',
    'Phnom Penh',
    'Phoenix',
    'Puebla',
    'Quebec City',
    'Qingdao',
    'Rawalpindi',
    'Recife',
    'Riyadh',
    'Rome',
    'Rotterdam',
    'Sacramento',
    'Salvador',
    'San Antonio',
    'San Diego',
    'San Francisco',
    'San Jose',
    'Santiago',
    'Sapporo',
    'Seattle',
    'Seoul',
    'Seville',
    'Shanghai',
    'Sharjah',
    'Shantou',
    'Shenyang',
    'Shijiazhuang',
    'Shenzhen',
    'Singapore',
    'Sofia',
    'Stuttgart',
    'Surabaya',
    'Sydney',
    'Taipei',
    'Tangshan',
    'Tashkent',
    'Tehran',
    'Thessaloniki',
    'Tianjin',
    'Tokyo',
    'Toronto',
    'Tripoli',
    'Tshwane',
    'Tunis',
    'Turin',
    'Ulaanbaatar',
    'Urumqi',
    'Valencia',
    'Vancouver',
    'Vienna',
    'Vientiane',
    'Vilnius',
    'Warsaw',
    'Washington',
    'Wuhan',
    'Xiamen',
    'Yokohama',
    'Zhengzhou',
    'Zurich',
  );

  private streets: RandomArray<string> = RandomArray.of(
    'Damrak',
    'Kalverstraat',
    'Spuistraat',
    'Leidsestraat',
    'P.C. Hooftstraat',
    'Utrechtsestraat',
    'Nieuwendijk',
    'Reguliersdwarsstraat',
    'Rozengracht',
    'Ceintuurbaan',
    'Broadway',
    'Fifth Avenue',
    'Wall Street',
    'Madison Avenue',
    'Park Avenue',
    'Lexington Avenue',
    'Seventh Avenue',
    'Canal Street',
    'Houston Street',
    '42nd Street',
    'George Street',
    'Pitt Street',
    'Oxford Street',
    'King Street',
    'Elizabeth Street',
    'Macquarie Street',
    'Castlereagh Street',
    'Market Street',
    'William Street',
    'Parramatta Road',
    'Oxford Street',
    'Regent Street',
    'Piccadilly',
    'Bond Street',
    'Fleet Street',
    'The Mall',
    'Kings Road',
    'Strand',
    'Baker Street',
    'Charing Cross Road',
    'Champs Elysees',
    'Rue de Rivoli',
    'Boulevard Saint Germain',
    'Boulevard Haussmann',
    'Avenue Montaigne',
    'Rue du Faubourg Saint Honore',
    'Rue de la Paix',
    'Rue de Vaugirard',
    'Boulevard des Capucines',
    'Rue Saint Honore',
    'Unter den Linden',
    'Kurfurstendamm',
    'Friedrichstrasse',
    'Karl Marx Allee',
    'Potsdamer Strasse',
    'Wilhelmstrasse',
    'Oranienburger Strasse',
    'Torstrasse',
    'Schonhauser Allee',
    'Mitte',
    'Charles Bridge',
    'Karlova',
    'Parizska',
    'Na Prikope',
    'Wenceslas Square',
    'Celetna',
    'Pařížská',
    'Letenska',
    'Mala Strana',
    'Nerudova',
    'Tverskaya',
    'Arbat',
    'New Arbat',
    'Kutuzovsky Prospekt',
    'Sadovoye Koltso',
    'Leninsky Prospekt',
    'Myasnitskaya',
    'Varvarka',
    'Petrovka',
    'Nikitsky Boulevard',
    'Via del Corso',
    'Via Veneto',
    'Via Condotti',
    'Via Nazionale',
    'Via Appia',
    'Via dei Fori Imperiali',
    'Via del Tritone',
    'Piazza Navona',
    'Via dei Coronari',
    'Via del Plebiscito',
    'Market Street',
    'Lombard Street',
    'Mission Street',
    'Van Ness Avenue',
    'California Street',
    'Geary Boulevard',
    'Broadway',
    'Folsom Street',
    'Haight Street',
    'Embarcadero',
    'Soweto Highway',
    'Rivonia Road',
    'Jan Smuts Avenue',
    'Pretoria Road',
    'Avenue Road',
    'Fourteenth Avenue',
    'William Nicol Drive',
    'Oxford Road',
    'Maponya Drive',
    'Joe Slovo Drive',
    'Ringstrasse',
    'Mariahilfer Strasse',
    'Kärntner Strasse',
    'Graben',
    'Getreidemarkt',
    'Landstraßer Hauptstraße',
    'Praterstrasse',
    'Währinger Straße',
    'Favoritenstrasse',
    'Gumpendorfer Strasse',
    'La Rambla',
    'Passeig de Gràcia',
    'Avinguda Diagonal',
    'Carrer de Balmes',
    'Carrer de Mallorca',
    'Carrer de València',
    'Via Laietana',
    'Gran Via de les Corts Catalanes',
    'Ronda de Sant Pere',
    'Carrer dArago',
    'Gran Via',
    'Paseo del Prado',
    'Calle Alcalá',
    'Calle de Serrano',
    'Calle de Atocha',
    'Calle de Fuencarral',
    'Paseo de la Castellana',
    'Calle de las Huertas',
    'Calle de Preciados',
    'Calle de Goya',
    'Ocean Drive',
    'Collins Avenue',
    'Biscayne Boulevard',
    'Washington Avenue',
    'Brickell Avenue',
    'Flagler Street',
    'Calle Ocho',
    'Fifth Street',
    'Lincoln Road',
    'Arthur Godfrey Road',
    'Paseo de la Reforma',
    'Avenida Insurgentes',
    'Madero Street',
    'Roma-Condesa Street',
    'Paseo de la Reforma',
    'Avenida Juárez',
    'Avenida Chapultepec',
    'Calzada de Tlalpan',
    'Avenida Revolución',
    'Calzada de los Misterios',
    'Nevsky Prospekt',
    'Ligovsky Prospekt',
    'Moskovsky Prospekt',
    'Sadovaya Street',
    'Bolshaya Morskaya Street',
    'Liteyny Prospekt',
    'Zvenigorodskaya Street',
    'Kamennoostrovsky Prospekt',
    'Prospekt Rimskogo Korsakova',
    'Chernishevskogo Prospekt',
    'Pikk Street',
    'Viru Street',
    'Vabaduse Valjak',
    'Toom-Kooli Street',
    'Lai Street',
    'Vene Street',
    'Harju Street',
    'Rataskaevu Street',
    'Müürivahe Street',
    'Kaarli Puiestee',
    'Karl Johans Gate',
    'Akergata',
    'Bogstadveien',
    'Markveien',
    'Grünerløkka Street',
    'Storgata',
    'Drammensveien',
    'Holbergs plass',
    'Torggata',
    'Kristian Augusts Gate',
    'Drottninggatan',
    'Kungsgatan',
    'Sveavägen',
    'Storgatan',
    'Regeringsgatan',
    'Vasagatan',
    'Biblioteksgatan',
    'Götgatan',
    'Hornsgatan',
    'Birger Jarlsgatan',
    'Avenida da Liberdade',
    'Rua Augusta',
    'Rua Garrett',
    'Rua do Ouro',
    'Rua da Prata',
    'Rua das Portas de Santo Antão',
    'Avenida 24 de Julho',
    'Rua do Carmo',
    'Avenida Almirante Reis',
    'Rua de São Bento',
    'Strøget',
    'Gammel Kongevej',
    'Vesterbrogade',
    'Østerbrogade',
    'Nørrebrogade',
    'Købmagergade',
    'Frederiksborggade',
    'Amagerbrogade',
    'Bredgade',
    'Studiestræde',
    'Istiklal Caddesi',
    'Bagdat Caddesi',
    'Vatan Caddesi',
    'Halaskargazi Caddesi',
    'Nispetiye Caddesi',
    'Tarlabaşı Bulvarı',
    'Fevzi Paşa Caddesi',
    'Valikonağı Caddesi',
    'Abdi İpekçi Caddesi',
    'Meclisi Mebusan Caddesi',
    'Omotesando',
    'Takeshita Street',
    'Ginza Dori',
    'Chuo Dori',
    'Meiji Dori',
    'Shibuya Center Gai',
    'Aoyama Dori',
    'Yasukuni Dori',
    'Hibiya Dori',
    'Showa Dori',
    'Gangnam-daero',
    'Teheran-ro',
    'Insa-dong',
    'Myeongdong-gil',
    'Jongno',
    'Itaewon-ro',
    'Dongdaemun-ro',
    'Namdaemun-ro',
    'Euljiro',
    'Mapo-daero',
    'Orchard Road',
    'Bukit Timah Road',
    'Serangoon Road',
    'Victoria Street',
    'North Bridge Road',
    'South Bridge Road',
    'Tanjong Pagar Road',
    'Beach Road',
    'Cecil Street',
    'Telok Ayer Street',
    'Yonge Street',
    'Queen Street West',
    'King Street West',
    'Bloor Street',
    'Bay Street',
    'Dundas Street',
    'Spadina Avenue',
    'Front Street',
    'College Street',
    'University Avenue',
    'Avenida 9 de Julio',
    'Avenida Corrientes',
    'Avenida de Mayo',
    'Calle Florida',
    'Avenida Santa Fe',
    'Avenida Rivadavia',
    'Avenida Callao',
    'Avenida del Libertador',
    'Avenida Belgrano',
    'Avenida San Juan',
    'Avenida Arequipa',
    'Avenida Larco',
    'Avenida Javier Prado',
    'Avenida Abancay',
    'Avenida Benavides',
    'Avenida Brasil',
    'Avenida Salaverry',
    'Avenida Alfonso Ugarte',
    'Avenida Tacna',
    'Jirón de la Unión',
    'Sukhumvit Road',
    'Silom Road',
    'Rama IV Road',
    'Ratchadaphisek Road',
    'Phetchaburi Road',
    'Charoen Krung Road',
    'Yaowarat Road',
    'Rama I Road',
    'Lat Phrao Road',
    'Thanon Phaya Thai',
    'Sheikh Zayed Road',
    'Al Wasl Road',
    'Jumeirah Beach Road',
    'Al Khail Road',
    'Emirates Road',
    'Al Rigga Road',
    'Baniyas Road',
    'Al Maktoum Road',
    'Airport Road',
    'Trade Centre Road',
    'Michigan Avenue',
    'State Street',
    'Lake Shore Drive',
    'Wacker Drive',
    'Clark Street',
    'Dearborn Street',
    'Halsted Street',
    'Roosevelt Road',
    'Ashland Avenue',
    'Division Street',
    'Jalan Bukit Bintang',
    'Jalan Ampang',
    'Jalan Raja Chulan',
    'Jalan Tun Razak',
    'Jalan Sultan Ismail',
    'Jalan Pudu',
    'Jalan TAR',
    'Jalan Petaling',
    'Jalan Raja Laut',
    'Jalan Kuching',
  );

  private countries: RandomArray<{ name: string; alpha2: string; alpha3: string }> = RandomArray.of(
    { name: 'Afghanistan', alpha2: 'AF', alpha3: 'AFG' },
    { name: 'Algeria', alpha2: 'DZ', alpha3: 'DZA' },
    { name: 'Angola', alpha2: 'AO', alpha3: 'AGO' },
    { name: 'Argentina', alpha2: 'AR', alpha3: 'ARG' },
    { name: 'Australia', alpha2: 'AU', alpha3: 'AUS' },
    { name: 'Austria', alpha2: 'AT', alpha3: 'AUT' },
    { name: 'Azerbaijan', alpha2: 'AZ', alpha3: 'AZE' },
    { name: 'Bangladesh', alpha2: 'BD', alpha3: 'BGD' },
    { name: 'Belarus', alpha2: 'BY', alpha3: 'BLR' },
    { name: 'Belgium', alpha2: 'BE', alpha3: 'BEL' },
    { name: 'Benin', alpha2: 'BJ', alpha3: 'BEN' },
    { name: 'Bolivia', alpha2: 'BO', alpha3: 'BOL' },
    { name: 'Brazil', alpha2: 'BR', alpha3: 'BRA' },
    { name: 'Bulgaria', alpha2: 'BG', alpha3: 'BGR' },
    { name: 'Burkina Faso', alpha2: 'BF', alpha3: 'BFA' },
    { name: 'Burundi', alpha2: 'BI', alpha3: 'BDI' },
    { name: 'Cambodia', alpha2: 'KH', alpha3: 'KHM' },
    { name: 'Cameroon', alpha2: 'CM', alpha3: 'CMR' },
    { name: 'Canada', alpha2: 'CA', alpha3: 'CAN' },
    { name: 'Chad', alpha2: 'TD', alpha3: 'TCD' },
    { name: 'Chile', alpha2: 'CL', alpha3: 'CHL' },
    { name: 'China', alpha2: 'CN', alpha3: 'CHN' },
    { name: 'Colombia', alpha2: 'CO', alpha3: 'COL' },
    { name: 'Congo', alpha2: 'CG', alpha3: 'COG' },
    { name: 'Costa Rica', alpha2: 'CR', alpha3: 'CRI' },
    { name: 'Cuba', alpha2: 'CU', alpha3: 'CUB' },
    { name: 'Czech Republic', alpha2: 'CZ', alpha3: 'CZE' },
    { name: 'DR Congo', alpha2: 'CD', alpha3: 'COD' },
    { name: 'Denmark', alpha2: 'DK', alpha3: 'DNK' },
    { name: 'Dominican Republic', alpha2: 'DO', alpha3: 'DOM' },
    { name: 'Ecuador', alpha2: 'EC', alpha3: 'ECU' },
    { name: 'Egypt', alpha2: 'EG', alpha3: 'EGY' },
    { name: 'El Salvador', alpha2: 'SV', alpha3: 'SLV' },
    { name: 'Ethiopia', alpha2: 'ET', alpha3: 'ETH' },
    { name: 'Finland', alpha2: 'FI', alpha3: 'FIN' },
    { name: 'France', alpha2: 'FR', alpha3: 'FRA' },
    { name: 'Germany', alpha2: 'DE', alpha3: 'DEU' },
    { name: 'Ghana', alpha2: 'GH', alpha3: 'GHA' },
    { name: 'Greece', alpha2: 'GR', alpha3: 'GRC' },
    { name: 'Guatemala', alpha2: 'GT', alpha3: 'GTM' },
    { name: 'Guinea', alpha2: 'GN', alpha3: 'GIN' },
    { name: 'Haiti', alpha2: 'HT', alpha3: 'HTI' },
    { name: 'Honduras', alpha2: 'HN', alpha3: 'HND' },
    { name: 'Hungary', alpha2: 'HU', alpha3: 'HUN' },
    { name: 'India', alpha2: 'IN', alpha3: 'IND' },
    { name: 'Indonesia', alpha2: 'ID', alpha3: 'IDN' },
    { name: 'Iran', alpha2: 'IR', alpha3: 'IRN' },
    { name: 'Iraq', alpha2: 'IQ', alpha3: 'IRQ' },
    { name: 'Ireland', alpha2: 'IE', alpha3: 'IRL' },
    { name: 'Israel', alpha2: 'IL', alpha3: 'ISR' },
    { name: 'Italy', alpha2: 'IT', alpha3: 'ITA' },
    { name: 'Ivory Coast', alpha2: 'CI', alpha3: 'CIV' },
    { name: 'Japan', alpha2: 'JP', alpha3: 'JPN' },
    { name: 'Jordan', alpha2: 'JO', alpha3: 'JOR' },
    { name: 'Kazakhstan', alpha2: 'KZ', alpha3: 'KAZ' },
    { name: 'Kenya', alpha2: 'KE', alpha3: 'KEN' },
    { name: 'Kyrgyzstan', alpha2: 'KG', alpha3: 'KGZ' },
    { name: 'Laos', alpha2: 'LA', alpha3: 'LAO' },
    { name: 'Lebanon', alpha2: 'LB', alpha3: 'LBN' },
    { name: 'Liberia', alpha2: 'LR', alpha3: 'LBR' },
    { name: 'Libya', alpha2: 'LY', alpha3: 'LBY' },
    { name: 'Madagascar', alpha2: 'MG', alpha3: 'MDG' },
    { name: 'Malaysia', alpha2: 'MY', alpha3: 'MYS' },
    { name: 'Mali', alpha2: 'ML', alpha3: 'MLI' },
    { name: 'Mexico', alpha2: 'MX', alpha3: 'MEX' },
    { name: 'Morocco', alpha2: 'MA', alpha3: 'MAR' },
    { name: 'Mozambique', alpha2: 'MZ', alpha3: 'MOZ' },
    { name: 'Myanmar', alpha2: 'MM', alpha3: 'MMR' },
    { name: 'Nepal', alpha2: 'NP', alpha3: 'NPL' },
    { name: 'Netherlands', alpha2: 'NL', alpha3: 'NLD' },
    { name: 'New Zealand', alpha2: 'NZ', alpha3: 'NZL' },
    { name: 'Nicaragua', alpha2: 'NI', alpha3: 'NIC' },
    { name: 'Niger', alpha2: 'NE', alpha3: 'NER' },
    { name: 'Nigeria', alpha2: 'NG', alpha3: 'NGA' },
    { name: 'North Korea', alpha2: 'KP', alpha3: 'PRK' },
    { name: 'Norway', alpha2: 'NO', alpha3: 'NOR' },
    { name: 'Oman', alpha2: 'OM', alpha3: 'OMN' },
    { name: 'Pakistan', alpha2: 'PK', alpha3: 'PAK' },
    { name: 'Papua New Guinea', alpha2: 'PG', alpha3: 'PNG' },
    { name: 'Paraguay', alpha2: 'PY', alpha3: 'PRY' },
    { name: 'Peru', alpha2: 'PE', alpha3: 'PER' },
    { name: 'Philippines', alpha2: 'PH', alpha3: 'PHL' },
    { name: 'Poland', alpha2: 'PL', alpha3: 'POL' },
    { name: 'Portugal', alpha2: 'PT', alpha3: 'PRT' },
    { name: 'Romania', alpha2: 'RO', alpha3: 'ROU' },
    { name: 'Russia', alpha2: 'RU', alpha3: 'RUS' },
    { name: 'Rwanda', alpha2: 'RW', alpha3: 'RWA' },
    { name: 'Saudi Arabia', alpha2: 'SA', alpha3: 'SAU' },
    { name: 'Senegal', alpha2: 'SN', alpha3: 'SEN' },
    { name: 'Serbia', alpha2: 'RS', alpha3: 'SRB' },
    { name: 'Sierra Leone', alpha2: 'SL', alpha3: 'SLE' },
    { name: 'Singapore', alpha2: 'SG', alpha3: 'SGP' },
    { name: 'Slovakia', alpha2: 'SK', alpha3: 'SVK' },
    { name: 'Somalia', alpha2: 'SO', alpha3: 'SOM' },
    { name: 'South Africa', alpha2: 'ZA', alpha3: 'ZAF' },
    { name: 'South Korea', alpha2: 'KR', alpha3: 'KOR' },
    { name: 'South Sudan', alpha2: 'SS', alpha3: 'SSD' },
    { name: 'Spain', alpha2: 'ES', alpha3: 'ESP' },
    { name: 'Sri Lanka', alpha2: 'LK', alpha3: 'LKA' },
    { name: 'Sudan', alpha2: 'SD', alpha3: 'SDN' },
    { name: 'Sweden', alpha2: 'SE', alpha3: 'SWE' },
    { name: 'Switzerland', alpha2: 'CH', alpha3: 'CHE' },
    { name: 'Syria', alpha2: 'SY', alpha3: 'SYR' },
    { name: 'Tajikistan', alpha2: 'TJ', alpha3: 'TJK' },
    { name: 'Tanzania', alpha2: 'TZ', alpha3: 'TZA' },
    { name: 'Thailand', alpha2: 'TH', alpha3: 'THA' },
    { name: 'Togo', alpha2: 'TG', alpha3: 'TGO' },
    { name: 'Tunisia', alpha2: 'TN', alpha3: 'TUN' },
    { name: 'Turkey', alpha2: 'TR', alpha3: 'TUR' },
    { name: 'Turkmenistan', alpha2: 'TM', alpha3: 'TKM' },
    { name: 'Uganda', alpha2: 'UG', alpha3: 'UGA' },
    { name: 'Ukraine', alpha2: 'UA', alpha3: 'UKR' },
    { name: 'United Kingdom', alpha2: 'GB', alpha3: 'GBR' },
    { name: 'United States', alpha2: 'US', alpha3: 'USA' },
    { name: 'Uzbekistan', alpha2: 'UZ', alpha3: 'UZB' },
    { name: 'Venezuela', alpha2: 'VE', alpha3: 'VEN' },
    { name: 'Vietnam', alpha2: 'VN', alpha3: 'VNM' },
    { name: 'Yemen', alpha2: 'YE', alpha3: 'YEM' },
    { name: 'Zambia', alpha2: 'ZM', alpha3: 'ZMB' },
    { name: 'Zimbabwe', alpha2: 'ZW', alpha3: 'ZWE' },
  );

  /**
   * Return a street name of one of the more famous streets around the world. The names do not include quotes or non latin characters
   */
  get street() {
    return this.streets.random();
  }

  /**
   * Return a city name of one of the more famous cities around the world. The names do not include quotes or non latin characters
   */
  get city() {
    return this.cities.random();
  }

  /**
   * Return a country name from a list of the most populated countries of the world. The names do not include quotes or non latin characters
   */
  get country() {
    return this.countries.random().name;
  }

  /**
   * Return a 2-letter country code from a list of the most populated countries of the world. The names do not include quotes or non latin characters
   */
  get alpha2() {
    return this.countries.random().alpha2;
  }

  /**
   * Return a 3-letter country code from a list of the most populated countries of the world. The names do not include quotes or non latin characters
   */
  get alpha3() {
    return this.countries.random().alpha3;
  }

  /**
   * Return an object with a name, alpha2 and alpha3 property from a list of the most populated countries of the world. The names do not include quotes or non latin characters.
   * Can be used if you need both the name and the code for the same country
   */
  get countryObject(): { name: string; alpha2: string; alpha3: string } {
    return this.countries.random();
  }
}

$random.address = new Address();
